name: master

on:
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
        env:
          CI: true

  publish:
    needs: test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get git info
        run: |
          git rev-parse --abbrev-ref HEAD
          git remote --verbose
          git checkout

      - name: Configure git
        run: |
          git config user.email 'nathanblair@users.noreply.github.com'
          git config user.name "Nathan Blair"

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      - run: npx jsdoc -R README.md -P package.json -d docs lib/*

      - name: Git Commit
        run: |
          git add docs
          git commit -m "Updated documentation"

      - run: npm version patch

      - run: git log -n 3

      - run: git push

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

