name: is-version-incremented

on:
  push:
    branches:
      - 'develop'

jobs:
  is-version-incremented:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compare working package version to production version
        run: |
          workingVer=$(awk '/version/ { print $2 }' RS=',\n' package.json)
          repoName=$(awk '/name/ { print $3 }' RS=',\n' package.json)
          prodVer=$(npm view ${repoName//\"/} version)

          [[ $workingVer == ${prodVer//\"/} ]]

