name: issue-created-test

on:
  issue_comment:
    types:
      - created

jobs:
  test-issue-creation-event:
    if: |
      github.event.comment.author_association == 'COLLABORATOR'
      && github.event.issue.pull_request != 0
      && github.event.comment.body == 'test issue create action'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - name: Get the base branch of the PR
        run: |
          echo Requesting PR base branch...
          branch=$(curl $PR_URL | jq -r '.head.ref')
          echo PR base branch: $branch
          echo "::set-env name=BRANCH::$branch"
        env:
          PR_URL: ${{ github.event.issue.pull_request.url }}

      - name: Checkout the base branch
        run: |
          echo git checkout $branch
