name: on-demand-test

on:
  issue_comment:
    types:
      - created

jobs:
  on-demand-test:
    if: |
      github.event.comment.author_association == 'COLLABORATOR'
      && github.event.issue.pull_request != 0
      && github.event.comment.body == 'run tests'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - name: Get the base branch of the PR
        run: |
          echo Requesting PR base branch...
          branch=$(curl $PR_URL | jq -r '.head.ref')
          echo PR base branch: $branch
          echo "::set-env name=BRANCH::$branch"
        env:
          PR_URL: ${{ github.event.issue.pull_request.url }}

      - name: Checkout the base branch
        # TODO add checkout options that limit what is checked out (only last commit)
        run: |
          git checkout $branch

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and test
        run: |
          npm test
          npm ci
        env:
          CI: true

