name: on-demand-test

on:
  issue_comment:
    types:
      - created

jobs:
  on-demand-test:
    if: |
      github.event.comment.body == 'run tests' &&
      github.event.comment.author_association == 'COLLABORATOR'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - name: Check that comment came from PR thread
        run: |
          echo Checking that comment came from a PR thread...
          [ -z "${HTML_URL##https://github.com/SonicOriginalSoftware/jester/pull}" ]
        env:
          HTML_URL: ${{ github.event.comment.html_url }}

      - name: Get the base branch of the PR
        run: |
          branch="TODO"
          echo PR Branch: $branch
          echo "::set-env name=branch::$branch"

      - name: Checkout the base branch
        # TODO add checkout options that limit what is checked out (only last commit)
        run: |
          git checkout $branch

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and test
        run: |
          npm test
          npm ci
        env:
          CI: true

