name: on-demand-test

on:
  issue_comment:
    types:
      - created

jobs:
  on-demand-test:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, 'Test')

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - name: Parse branch
        run: |
          branch="${BODY/Test/ }"
          echo $branch
        env:
          BODY: ${{ github.event.comment.body }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ branch }}

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - run: npm test
        env:
          CI: true

