name: Create Update PR

on:
  pull_request:
    types:
      - opened

jobs:
  create-on-demand-comment:
    if: |
      github.event.pull_request.head.ref == 'develop'
      && github.event.pull_request.base.ref == 'prod'

    runs-on: ubuntu-latest

    steps:
      - name: Create the on-demand test comment
        run: |
          curl --request POST --url ${{ github.event.issue.comments_url }} \
            --header 'authorization: Bearer ${{ github.token }}' \
            --header 'content-type: application/json' \
            --data "run tests"

  create-set-version-comment:
    if: |
      github.event.pull_request.head.ref == 'develop'
      && github.event.pull_request.base.ref == 'prod'

    runs-on: ubuntu-latest

    steps:
      - name: Create the set-version comment
        run: |
          curl --request POST --url ${{ github.event.issue.comments_url }} \
            --header 'authorization: Bearer ${{ github.token }}' \
            --header 'content-type: application/json' \
            --data "npm version"

