name: publish

on:
  push:
    branches:
      - 'prod'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout prod branch
        run: |
          git clone --branch=prod --depth=1 ${{ github.repositoryUrl }} .

      # TODO Assign the appropriate registry to publish to
      - name: Publish
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
          REGISTRY_URL: 'https://registry.npmjs.org'

      - name: Initialize docs directory
        run: |
          git clone --depth=1 --branch=master $REPO_URL docs
          rm -rf docs/*
        env:
          REPO_URL: ${{ github.repositoryUrl }}

      - name: Generate docs
        run: |
          npm ci
          npm run gen-docs

      - name: Update the live docs
        run: |
          cd docs
          git add --all
          git commit -m "Updated docs"
          git push

