name: published

on: page_build

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install and generate docs
        run: |
          npm ci
          npx jsdoc -R README.md -P package.json -d docs lib/*

      - name: Commit updated docs
        run: |
          git add docs
          git commit -m "Updated documentation"

      - name: Increment version on master branch
        run: npm version patch

      - run: git log -n 3

      - run: git push origin master

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

      - name: Checkout dev branch
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Increment jester version on dev branch
        run: |
          npm version patch
          git push origin dev

