name: version-check

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  check-version:
    if: |
      github.event.pull_request.head.ref == 'develop'
      && github.event.pull_request.base.ref == 'prod'

    runs-on: ubuntu-latest

    steps:
      - name: Clone the pull-request branch
        run: |
          echo Cloning branch: ${{ github.event.pull_request.head.ref }}
          git clone --branch=${{ github.event.pull_request.head.ref }} --depth=1 ${{ github.repositoryUrl }} .

      - name: Get working version
        run: |
          workingVer=$(awk '/version/ { print $2 }' RS=',\n' package.json)
          workingVer=${workingVer//\"/}

          echo Working Version: $workingVer
          echo "::set-env name=WORKING_VER::$workingVer"

      - name: Compare working package version to PR Title
        run: |
          prTitleVer="${{ github.event.pull_request.title }}"
          prTitleVer=${prTitleVer#[V|v|Version|version]}
          prTitleVer=${prTitleVer//\ /}

          echo PR Title Version: $prTitleVer

          [[ $WORKING_VER == $prTitleVer ]]

      - name: Check that the working version is not the same as the production version
        run: |
          repoName=$(awk '/name/ { print $3 }' RS=',\n' package.json)
          prodVer=$(npm view ${repoName//\"/} version)

          echo Prod Version: $prodVer
          echo "::set-env name=PROD_VER::$prodVer"

          [[ $WORKING_VER != $prodVer ]]

      - name: Check that the working version is a valid semver string
        run: |
          npx semver $WORKING_VER

      - name: Check that the working version is greater than the production version
        run: |
          sorted=$(npx semver $WORKING_VER $PROD_VER)

          checkSort="$PROD_VER
          $WORKING_VER"

          echo Sorted:
          echo $sorted
          echo
          echo Checked Sort:
          echo $checkSort

          # Verify that the order is correct
          [[ $sorted == $checkSort ]]

