name: version-is-incremented

on:
  push:
    branches:
      - 'develop'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compare working package version to production version
        run: |
          workingVer=$(awk '/version/ { print $2 }' RS=',\n' package.json)
          prodVer=$(npm view @${{ github.repository }} version)

          [[ $workingVer == \"$prodVer\" ]]

